package projet;

public enum Categories {
	AUDIOVISUEL_SPECTACLE_CINEMA,
	ARMEE_SECURITE,
	AUDIT,
	BANQUE_ASSURANCE,
	CHIMIE_PHARMACIE,
	ENERGIE,
	HOTELLERIE_RESTORATION_TOURISME,
	ENSEIGNEMENT,
	INFORMATIQUE_NUMERIQUE_RESEAUX,
	LOGISTIQUE_TRANSPORT,
	MAINTENANCE_ENTRETIEN,
	MARKETING_PUBLICITE_COMMUNICATION,
	MECANIQUE,
	MATERIAUX_TRANSFORMATION,
	SANTE_MEDICAL,
	SOCIAL,
	SPORT_LOISIRS
}
